title: UML Embedded Site
email: patrick_hoey1@student.uml.edu
description: >- # this means to ignore newlines until "baseurl:"
  UML Embedded Club Site
#Below was modified according to github link shown on line #10
domain: uml-embedded.github.io	#Added according to line #10
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "uml-embedded.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-theme-midnight

plugins:
  - jekyll-feed

